n_runs: 2
distances_methods: ["matching_dist"]
# base_output_dir: "tests/.temp/clustering"
slurm_job_name_prefix: null
slurm_partition: null
wandb_project: "spd"
wandb_entity: "goodfire"
create_git_snapshot: false
clustering_run_config_path: "spd/clustering/configs/crc/simplestories_dev.json"