clustering_run_config_path: "spd/clustering/configs/crc/ss_llama_simple_mlp-1L.json"
# clustering_run_config_path: "spd/clustering/configs/crc/resid_mlp2.json"
n_runs: 10
distances_methods: ["perm_invariant_hamming"]
base_output_dir: "/mnt/polished-lake/spd/clustering"
slurm_job_name_prefix: "spd"
slurm_partition: "h200-reserved"
wandb_project: "spd"
wandb_entity: "goodfire"
create_git_snapshot: true