Male pronouns:
  - h.1.mlp.down_proj:798
  - h.1.mlp.c_fc:144
  - h.1.attn.o_proj:82

Question marks:
  - h.1.mlp.down_proj:534
  - h.1.mlp.c_fc:891
  - h.1.attn.o_proj:6

Memorized template:
  - h.1.mlp.down_proj:136
